# Site settings
title: "Blake Grotewold"
author:
    name: "Blake Grotewold"
    email: "hello@grote.world"
    url: "https://grote.world"
    location: "39.167113, -86.534240"
    avatar: "/assets/avatar.png"
    github: "groteworld"
    vine: "groteworld"
    twitter: "groteworld"
    bitcoin: "18AnsQDidF7zzgNFWQ39NMje1fD6RcKwhH"
description: "Game Dev, Open Sourcer, Pythonista"
baseurl: ""
url: "https://grote.world"
permalink: none
timezone: America/Indiana/Indianapolis

# Build settings
markdown: kramdown
sass:
    sass_dir: assets
    style: :compressed

exclude: [vendor]
